name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: npm install

      - name: Replace Firebase Config
        run: |
          sed -i "s|FIREBASE_DATABASE_URL|${{ secrets.FIREBASE_DATABASE_URL }}|g" source/about/index.md
          sed -i "s|FIREBASE_PROJECT_ID|${{ secrets.FIREBASE_PROJECT_ID }}|g" source/about/index.md
          sed -i "s|FIREBASE_API_KEY|${{ secrets.FIREBASE_API_KEY }}|g" source/about/index.md
          sed -i "s|FIREBASE_AUTH_DOMAIN|${{ secrets.FIREBASE_AUTH_DOMAIN }}|g" source/about/index.md
          sed -i "s|FIREBASE_STORAGE_BUCKET|${{ secrets.FIREBASE_STORAGE_BUCKET }}|g" source/about/index.md
          sed -i "s|FIREBASE_MESSAGING_SENDER_ID|${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}|g" source/about/index.md
          sed -i "s|FIREBASE_APP_ID|${{ secrets.FIREBASE_APP_ID }}|g" source/about/index.md

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
